[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Zowie", email = "me@zowie.cx"},
]
dependencies = [
    "tqdm>=4.64.1,<5.0.0",
    "requests>=2.28.2,<3.0.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
